#!/usr/bin/env python3
"""Generate thumbnail grid images from PowerPoint slides.

Converts a .pptx to PDF via LibreOffice, then to JPEG images via pdftoppm,
and optionally composites them into a grid using Pillow.

Usage:
    python thumbnail.py presentation.pptx [--grid grid_output.jpg] [--cols 4] [--dpi 150]

Without --grid, outputs individual slide-NNN.jpg files.
With --grid, also creates a single grid image for quick visual review.

Requirements:
    - soffice (LibreOffice) on PATH
    - pdftoppm (poppler-utils) on PATH
    - Pillow (pip install Pillow)
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    Image = None


def _find_binary(name):
    """Check if a binary is on PATH."""
    return shutil.which(name)


def _run(cmd, cwd=None):
    """Run a command, return (returncode, stdout, stderr)."""
    env = os.environ.copy()
    # Headless mode for LibreOffice in sandboxed environments
    env.setdefault("SAL_USE_VCLPLUGIN", "svp")

    result = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )
    return result.returncode, result.stdout, result.stderr


def convert_to_images(pptx_path, output_dir, dpi=150):
    """Convert .pptx → PDF → JPEG images.

    Returns list of image file paths in slide order.
    """
    pptx_path = Path(pptx_path).resolve()
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not _find_binary("soffice"):
        print("Error: soffice (LibreOffice) not found on PATH", file=sys.stderr)
        sys.exit(1)
    if not _find_binary("pdftoppm"):
        print("Error: pdftoppm (poppler-utils) not found on PATH", file=sys.stderr)
        sys.exit(1)

    # Step 1: Convert .pptx to PDF via LibreOffice
    with tempfile.TemporaryDirectory() as tmpdir:
        rc, out, err = _run([
            "soffice", "--headless", "--convert-to", "pdf",
            "--outdir", tmpdir,
            str(pptx_path),
        ])
        if rc != 0:
            print(f"soffice failed (rc={rc}): {err}", file=sys.stderr)
            sys.exit(1)

        pdf_name = pptx_path.stem + ".pdf"
        pdf_path = Path(tmpdir) / pdf_name
        if not pdf_path.exists():
            # Sometimes soffice changes the name
            pdfs = list(Path(tmpdir).glob("*.pdf"))
            if pdfs:
                pdf_path = pdfs[0]
            else:
                print("Error: PDF not generated by soffice", file=sys.stderr)
                sys.exit(1)

        # Step 2: Convert PDF pages to JPEG via pdftoppm
        prefix = str(output_dir / "slide")
        rc, out, err = _run([
            "pdftoppm", "-jpeg", "-r", str(dpi),
            str(pdf_path), prefix,
        ])
        if rc != 0:
            print(f"pdftoppm failed (rc={rc}): {err}", file=sys.stderr)
            sys.exit(1)

    # Collect generated images in sorted order
    images = sorted(output_dir.glob("slide-*.jpg"))
    if not images:
        # pdftoppm may use different naming on some systems
        images = sorted(output_dir.glob("slide*.jpg"))

    return [str(p) for p in images]


def create_grid(image_paths, output_path, cols=4):
    """Composite slide images into a grid.

    Args:
        image_paths: List of JPEG file paths in order
        output_path: Path for the grid image
        cols: Number of columns in the grid
    """
    if Image is None:
        print("Error: Pillow not installed. Run: pip install Pillow", file=sys.stderr)
        sys.exit(1)

    if not image_paths:
        print("Warning: no images to grid", file=sys.stderr)
        return

    # Open all images, determine consistent size
    imgs = [Image.open(p) for p in image_paths]
    thumb_w = min(img.width for img in imgs)
    thumb_h = min(img.height for img in imgs)

    # Scale to consistent thumbnail size
    target_w = min(thumb_w, 480)
    scale = target_w / thumb_w
    target_h = int(thumb_h * scale)

    resized = [img.resize((target_w, target_h), Image.LANCZOS) for img in imgs]

    rows = (len(resized) + cols - 1) // cols
    padding = 4
    label_h = 20

    grid_w = cols * target_w + (cols + 1) * padding
    grid_h = rows * (target_h + label_h) + (rows + 1) * padding

    grid = Image.new("RGB", (grid_w, grid_h), (255, 255, 255))

    for i, img in enumerate(resized):
        row = i // cols
        col = i % cols
        x = padding + col * (target_w + padding)
        y = padding + row * (target_h + label_h + padding)
        grid.paste(img, (x, y))

        # Add slide number label below each thumbnail
        try:
            from PIL import ImageDraw
            draw = ImageDraw.Draw(grid)
            draw.text(
                (x + target_w // 2, y + target_h + 2),
                f"Slide {i}",
                fill=(100, 100, 100),
                anchor="mt",
            )
        except Exception:
            pass  # Skip labels if font rendering fails

    for img in imgs:
        img.close()

    grid.save(str(output_path), "JPEG", quality=90)
    return str(output_path)


def main():
    parser = argparse.ArgumentParser(description="Generate slide thumbnails from PowerPoint")
    parser.add_argument("pptx", help="Path to .pptx file")
    parser.add_argument("--grid", help="Output path for grid image (optional)")
    parser.add_argument("--cols", type=int, default=4, help="Grid columns (default: 4)")
    parser.add_argument("--dpi", type=int, default=150, help="Render DPI (default: 150)")
    parser.add_argument("--outdir", help="Output directory for individual slides (default: same as .pptx)")

    args = parser.parse_args()

    pptx_path = Path(args.pptx)
    if not pptx_path.exists():
        print(f"Error: {pptx_path} not found", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(args.outdir) if args.outdir else pptx_path.parent
    images = convert_to_images(pptx_path, output_dir, dpi=args.dpi)

    print(f"Generated {len(images)} slide image(s) in {output_dir}")
    for img in images:
        print(f"  {img}")

    if args.grid:
        grid_path = create_grid(images, args.grid, cols=args.cols)
        if grid_path:
            print(f"Grid image → {grid_path}")


if __name__ == "__main__":
    main()
